package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name="employee"
    ,catalog="project1"
)
public class Employee  implements java.io.Serializable {


     private Integer id;
     private Departments departments;
     private Date createdOn;
     private String email;
     private String name;
     private String status;
     private Date updatedOn;
     private Set<Purchaserequest> purchaserequests = new HashSet<Purchaserequest>(0);
     private Set<Holdings> holdingses = new HashSet<Holdings>(0);
     private Set<Resourcerequest> resourcerequests = new HashSet<Resourcerequest>(0);

    public Employee() {
    }

    public Employee(Departments departments, Date createdOn, String email, String name, String status, Date updatedOn, Set<Purchaserequest> purchaserequests, Set<Holdings> holdingses, Set<Resourcerequest> resourcerequests) {
       this.departments = departments;
       this.createdOn = createdOn;
       this.email = email;
       this.name = name;
       this.status = status;
       this.updatedOn = updatedOn;
       this.purchaserequests = purchaserequests;
       this.holdingses = holdingses;
       this.resourcerequests = resourcerequests;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="department_id")
    public Departments getDepartments() {
        return this.departments;
    }
    
    public void setDepartments(Departments departments) {
        this.departments = departments;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdOn", length=10)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updatedOn", length=10)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Purchaserequest> getPurchaserequests() {
        return this.purchaserequests;
    }
    
    public void setPurchaserequests(Set<Purchaserequest> purchaserequests) {
        this.purchaserequests = purchaserequests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Holdings> getHoldingses() {
        return this.holdingses;
    }
    
    public void setHoldingses(Set<Holdings> holdingses) {
        this.holdingses = holdingses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set<Resourcerequest> getResourcerequests() {
        return this.resourcerequests;
    }
    
    public void setResourcerequests(Set<Resourcerequest> resourcerequests) {
        this.resourcerequests = resourcerequests;
    }




}


