package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Holdings generated by hbm2java
 */
@Entity
@Table(name="holdings"
    ,catalog="project1"
)
public class Holdings  implements java.io.Serializable {


     private Integer idholday;
     private Employee employee;
     private Resources resources;
     private Date createdOn;
     private Date updatedOn;
     private Boolean restartstatus;

    public Holdings() {
    }

    public Holdings(Employee employee, Resources resources, Date createdOn, Date updatedOn, Boolean restartstatus) {
       this.employee = employee;
       this.resources = resources;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
       this.restartstatus = restartstatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idholday", unique=true, nullable=false)
    public Integer getIdholday() {
        return this.idholday;
    }
    
    public void setIdholday(Integer idholday) {
        this.idholday = idholday;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resource_id")
    public Resources getResources() {
        return this.resources;
    }
    
    public void setResources(Resources resources) {
        this.resources = resources;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdOn", length=10)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updatedOn", length=10)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    
    @Column(name="restartstatus")
    public Boolean getRestartstatus() {
        return this.restartstatus;
    }
    
    public void setRestartstatus(Boolean restartstatus) {
        this.restartstatus = restartstatus;
    }




}


