package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Purchaserequest generated by hbm2java
 */
@Entity
@Table(name="purchaserequest"
    ,catalog="project1"
)
public class Purchaserequest  implements java.io.Serializable {


     private Integer id;
     private Employee employee;
     private String approvedBy;
     private Date createdOn;
     private String productName;
     private String updatedOn;
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public Purchaserequest() {
    }

    public Purchaserequest(Employee employee, String approvedBy, Date createdOn, String productName, String updatedOn, Set<Purchase> purchases) {
       this.employee = employee;
       this.approvedBy = approvedBy;
       this.createdOn = createdOn;
       this.productName = productName;
       this.updatedOn = updatedOn;
       this.purchases = purchases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="approvedBy", length=45)
    public String getApprovedBy() {
        return this.approvedBy;
    }
    
    public void setApprovedBy(String approvedBy) {
        this.approvedBy = approvedBy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdOn", length=10)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="productName", length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="updatedOn", length=45)
    public String getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(String updatedOn) {
        this.updatedOn = updatedOn;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="purchaserequest")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


