package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Purchase generated by hbm2java
 */
@Entity
@Table(name="purchase"
    ,catalog="project1"
)
public class Purchase  implements java.io.Serializable {


     private Integer id;
     private Purchaserequest purchaserequest;
     private Resources resources;
     private String authorizedBy;
     private String description;
     private Double price;

    public Purchase() {
    }

    public Purchase(Purchaserequest purchaserequest, Resources resources, String authorizedBy, String description, Double price) {
       this.purchaserequest = purchaserequest;
       this.resources = resources;
       this.authorizedBy = authorizedBy;
       this.description = description;
       this.price = price;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="purchaseRequest_Id")
    public Purchaserequest getPurchaserequest() {
        return this.purchaserequest;
    }
    
    public void setPurchaserequest(Purchaserequest purchaserequest) {
        this.purchaserequest = purchaserequest;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resources_Id")
    public Resources getResources() {
        return this.resources;
    }
    
    public void setResources(Resources resources) {
        this.resources = resources;
    }

    
    @Column(name="authorizedBy", length=45)
    public String getAuthorizedBy() {
        return this.authorizedBy;
    }
    
    public void setAuthorizedBy(String authorizedBy) {
        this.authorizedBy = authorizedBy;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="price", precision=22, scale=0)
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }




}


