package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resourcetype generated by hbm2java
 */
@Entity
@Table(name="resourcetype"
    ,catalog="project1"
)
public class Resourcetype  implements java.io.Serializable {


     private Integer id;
     private Date createdOn;
     private String name;
     private Date updatedOn;

    public Resourcetype() {
    }

    public Resourcetype(Date createdOn, String name, Date updatedOn) {
       this.createdOn = createdOn;
       this.name = name;
       this.updatedOn = updatedOn;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdOn", length=10)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updatedOn", length=10)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


