package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resources generated by hbm2java
 */
@Entity
@Table(name="resources"
    ,catalog="project1"
)
public class Resources  implements java.io.Serializable {


     private Integer id;
     private Date createdOn;
     private String description;
     private String name;
     private Integer resourceTypeId;
     private Date updateOn;
     private Boolean status;
     private Set<Resourcerequest> resourcerequests = new HashSet<Resourcerequest>(0);
     private Set<Holdings> holdingses = new HashSet<Holdings>(0);
     private Set<Purchase> purchases = new HashSet<Purchase>(0);

    public Resources() {
    }

    public Resources(Date createdOn, String description, String name, Integer resourceTypeId, Date updateOn, Boolean status, Set<Resourcerequest> resourcerequests, Set<Holdings> holdingses, Set<Purchase> purchases) {
       this.createdOn = createdOn;
       this.description = description;
       this.name = name;
       this.resourceTypeId = resourceTypeId;
       this.updateOn = updateOn;
       this.status = status;
       this.resourcerequests = resourcerequests;
       this.holdingses = holdingses;
       this.purchases = purchases;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdOn", length=10)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="resourceType_id")
    public Integer getResourceTypeId() {
        return this.resourceTypeId;
    }
    
    public void setResourceTypeId(Integer resourceTypeId) {
        this.resourceTypeId = resourceTypeId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updateOn", length=10)
    public Date getUpdateOn() {
        return this.updateOn;
    }
    
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }

    
    @Column(name="status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resources")
    public Set<Resourcerequest> getResourcerequests() {
        return this.resourcerequests;
    }
    
    public void setResourcerequests(Set<Resourcerequest> resourcerequests) {
        this.resourcerequests = resourcerequests;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resources")
    public Set<Holdings> getHoldingses() {
        return this.holdingses;
    }
    
    public void setHoldingses(Set<Holdings> holdingses) {
        this.holdingses = holdingses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="resources")
    public Set<Purchase> getPurchases() {
        return this.purchases;
    }
    
    public void setPurchases(Set<Purchase> purchases) {
        this.purchases = purchases;
    }




}


