package org.example.model;
// Generated Feb 6, 2023, 11:23:44 PM by Hibernate Tools 5.2.11.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Resourcerequest generated by hbm2java
 */
@Entity
@Table(name="resourcerequest"
    ,catalog="project1"
)
public class Resourcerequest  implements java.io.Serializable {


     private int id;
     private Employee employee;
     private Resources resources;
     private Date createdOn;
     private Date updatedOn;

    public Resourcerequest() {
    }

	
    public Resourcerequest(int id) {
        this.id = id;
    }
    public Resourcerequest(int id, Employee employee, Resources resources, Date createdOn, Date updatedOn) {
       this.id = id;
       this.employee = employee;
       this.resources = resources;
       this.createdOn = createdOn;
       this.updatedOn = updatedOn;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id")
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="resourse_id")
    public Resources getResources() {
        return this.resources;
    }
    
    public void setResources(Resources resources) {
        this.resources = resources;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="createdOn", length=10)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="updatedOn", length=10)
    public Date getUpdatedOn() {
        return this.updatedOn;
    }
    
    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }




}


